# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae8bb3649d5a6682201d0b8450b232b8ff75e409b200857c0680ac1214af53f137ccc8a8e7cc5287c4b6e1f5903c87c3e00f3f1348513f78272372b9671376ad

test:
  secret_key_base: 566c28b948507d1a95cedf5c4bbe72a266dcfbcde785115966bf3ca6a07e1d3c332048c2ec20518dfe017663305b632eb560f12b34bd3d612d436a2c36663ff2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
