# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9948bc0ceb6aeb465ca6235fb4a5fb75f558f9c2bc521c6fa03afc24c4e8a2b7037dac9badea0d00ffd9d0079fd793698d35611924fe2c6d516285fd06838b1e

test:
  secret_key_base: 2e057c30a0c8f1c674b53692a67777fef4be2570c325a9a52795723a2feb65c0ed30b6ecc89ba8c41e41cd14b35ae724c6bb78d44ecfc4298f5e4ba487c50703

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
