# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2a43baf279feaed314de5be64c6aa3cca26de04dc9d632ca796dfbc7bd566e8a2bbd0b05dd6a227c6ac54c69669a0649ebb4e65880b7a07c661b88cd6db9db9

test:
  secret_key_base: 2486075fb5c11c94ba2ca496a4d310987fdb4e82b98766ceabdc66bc62979bebe1b65b1cbc410bfba52406647e8ba2e6e92562a481adf44a8b18d289215b27d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
