# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a41f2ab00e6beeeb0117be9a8fe4d690337a24ecebccc70351216f2221713290f9fe3ef56efc5cc820e948dc100513c7a8053b01e384d109f7b8208e8b429cef

test:
  secret_key_base: 6b2b2815c75573c748b0931884891bf3f68e802a9bd069b6c1989dca5c500a7208c0c799a5f21eb80d2412caa0fc8387c02450c534aabb891b7dafe377342c4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
