# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ea5473ae5f057282dbd38f2290d961ddc23bdc1338d894fa573468ed62e50c082d69376018d0dc068b62c497a577a3d938dc38102ec1929648f4a6cf1535171

test:
  secret_key_base: 933ee55388f018725a598ddcfb8d4638e200d790f729e2a4363cd56b1036e8c66f9c5dd408c308862fb8d31343ad84e9b926688b86ab1733ff63747fd251b386

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
